name = "Effort"
uuid = "ace19e24-02c2-4bce-bc41-b57e89c0fc53"
version = "0.4.1"
authors = ["marcobonici <bonici.marco@gmail.com>"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
AbstractCosmologicalEmulators = "c83c1981-e5c4-4837-9eb8-c9b1572acfc6"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
FindFirstFunctions = "64ca27bc-2ba2-4a57-88aa-44e436879224"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LegendrePolynomials = "3db4a2ba-fc88-11e8-3e01-49c72059a882"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ADTypes = "1"
AbstractCosmologicalEmulators = "0.8"
Artifacts = "1"
ChainRulesCore = "1"
DataInterpolations = "8"
DifferentiationInterface = "0.6, 0.7"
FastGaussQuadrature = "1"
FindFirstFunctions = "1"
FiniteDifferences = "0.12"
ForwardDiff = "0.10, 1"
Integrals = "4"
JSON = "1"
LegendrePolynomials = "0.4"
LinearAlgebra = "1.10.0"
LoopVectorization = "0.12"
Lux = "1.24.0"
Memoization = "0.2"
Mooncake = "0.4, 0.5"
NPZ = "0.4"
OrdinaryDiffEqTsit5 = "1"
Random = "1.11.0"
SciMLSensitivity = "7"
SimpleChains = "0.4"
Static = "0.8, 1"
Test = "1.10"
Tullio = "0.3"
Zygote = "0.7"
julia = "1.10"

[extras]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
SimpleChains = "de6bee2f-e2f4-4ec7-b6ed-219cc6f6e9e5"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ADTypes", "DifferentiationInterface", "FiniteDifferences", "ForwardDiff", "Mooncake", "SciMLSensitivity", "SimpleChains", "Static", "Test"]
